Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/NegatedIf:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/PerlBackrefs:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LeadingCommentSpace:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Max: 160
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Bundler/OrderedGems:
  Enabled: false
