Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/NegatedIf:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
