Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/NegatedIf:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/PerlBackrefs:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/NegatedWhile:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LeadingCommentSpace:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Max: 160
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
