version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: large
    steps:
      - checkout
      - run: |
          echo 'podman() {' >> "$BASH_ENV"
          echo 'docker "$@"' >> "$BASH_ENV"
          echo '}' >> "$BASH_ENV"
          echo 'export -f podman' >> "$BASH_ENV"

          echo 'CI=true' >> podman/podman.env
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> podman/podman.env

          ./podman/create-network.sh

          ./podman/run-postgresql.sh
          ./podman/run-sidekiq-redis.sh

          ./podman/build-image.sh
          ./podman/setup-db.sh
          ./podman/run-tests.sh
workflows:
  version: 2
  doit:
    jobs:
      - test
