version: 2.1
jobs:
  test:
    docker:
      - image: fedora:latest
    resource_class: large
    environment:
      RAILS_ENV: test
      DATABASE_USER: gamocosm
      DATABASE_PASSWORD: 123
      DEVISE_SECRET_KEY: 1234abcd
      DIGITAL_OCEAN_API_KEY: abcd1234
      DIGITAL_OCEAN_SSH_PUBLIC_KEY_PATH: id_ed25519.pub
      CLOUDFLARE_API_TOKEN: 123abc
      CLOUDFLARE_EMAIL: test@test.com
      CLOUDFLARE_ZONE: abc123
      USER_SERVERS_DOMAIN: example.com
    steps:
      - checkout
      - run: |
        whoami
        pwd
      - run: |
        dnf -y install gcc gcc-c++ openssl-devel readline-devel zlib-devel
      - run: |
        git clone https://github.com/rbenv/rbenv.git rbenv
        mkdir rbenv/plugins
        git clone https://github.com/rbenv/ruby-build.git rbenv/plugins/ruby-build
        echo "PATH='$(pwd)/rbenv/bin:$PATH'" >> "$BASH_ENV"
      - run: |
        eval "$(rbenv init - bash)"
        rbenv install
      - run: |
        dnf -y install postgresql-devel
        bundle install
      - run: |
        dnf -y install postgresql-server postgresql-contrib memcached redis nodejs
      - run: |
        postgresql-setup --initdb --unit postgresql
      - run: |
        systemctl start postgresql
        systemctl start memcached
        systemctl start redis
      - run: |
        echo "*:*:*:$DATABASE_USER:$DATABASE_PASSWORD" > ~postgres/.pgpass
        chown postgres:postgres ~postgres/.pgpass
        chmod 600 ~postgres/.pgpass
        sudo --user postgres --login createuser --createdb --no-createrole --superuser --no-password gamocosm
        sed -i -e '1i local postgres,gamocosm_test gamocosm md5' /var/lib/pgsql/data/pg_hba.conf
        systemctl restart postgresql
      - run: |
        echo "*:*:*:$DATABASE_USER:$DATABASE_PASSWORD" > ~/.pgpass
        chmod 600 ~/.pgpass
      - run: |
        bundle exec rake db:setup
      - run: |
        ssh-keygen -t ed25519 -N '' -f id_ed25519
      - run: |
        bundle exec rake test
workflows:
  version: 2
  doit:
    jobs:
      - test
