version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: large
    steps:
      - checkout
      - run: |
          echo 'CI=true' >> template.env
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> template.env
          echo "SECRET_KEY_BASE=$(rails secret)" >> template.env

          source template.env

          ssh-keygen -t ed25519 -f id_gamocosm -N ''
          docker secret create gamocosm-ssh-key id_gamocosm

          docker network create gamocosm-network

          docker run --detach --rm --network gamocosm-network --name "$DATABASE_HOST" --env "POSTGRES_USER=$DATABASE_USER" --env "POSTGRES_PASSWORD=$DATABASE_PASSWORD" docker.io/postgres:14.5
          docker run --detach --rm --network gamocosm-network --name "$SIDEKIQ_REDIS_HOST" docker.io/redis:7.0.4

          ./sysadmin/build.sh

          docker run --rm --network gamocosm-network --env-file template.env --secret gamocosm-ssh-key,type=mount,target=/gamocosm/id_gamocosm gamocosm rails db:setup

          docker run --rm --network gamocosm-network --env-file template.env --secret gamocosm-ssh-key,type=mount,target=/gamocosm/id_gamocosm gamocosm rails test
workflows:
  version: 2
  doit:
    jobs:
      - test
