version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: large
    steps:
      - checkout
      - run: |
          cp template.env gamocosm.env
          echo 'CI=true' >> gamocosm.env
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> gamocosm.env
          echo "SECRET_KEY_BASE=$(openssl rand -hex 64)" >> gamocosm.env

          source gamocosm.env

          ssh-keygen -t ed25519 -f id_gamocosm -N ''

          DOCKER_BUILDKIT=1 docker build --file Containerfile --tag gamocosm --build-arg "secret_key_base=$SECRET_KEY_BASE" --secret id=gamocosm-ssh-key,src=id_gamocosm .

          docker network create gamocosm-network

          docker run --detach --rm --network gamocosm-network --name "$DATABASE_HOST" --env "POSTGRES_USER=$DATABASE_USER" --env "POSTGRES_PASSWORD=$DATABASE_PASSWORD" docker.io/postgres:14.5
          docker run --detach --rm --network gamocosm-network --name "$SIDEKIQ_REDIS_HOST" docker.io/redis:7.0.4

          docker run --detach --rm --network gamocosm-network --name gamocosm-test --env-file gamocosm.env --env RAILS_ENV=test gamocosm yes

          docker cp id_gamocosm gamocosm-test:/gamocosm/
          docker cp .git gamocosm-test:/gamocosm/

          docker exec gamocosm-test rails db:setup
          docker exec gamocosm-test rails test
