version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: large
    steps:
      - checkout
      - run: |
          source template.env

          echo 'CI=true' >> template.env
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> template.env

          ssh-keygen -t ed25519 -N "$DIGITAL_OCEAN_SSH_PRIVATE_KEY_PASSPHRASE" -f id_gamocosm

          docker network create gamocosm-network

          docker run --detach --rm --name gamocosm-database --network gamocosm-network --env "POSTGRES_USER=$DATABASE_USER" --env "POSTGRES_PASSWORD=$DATABASE_PASSWORD" docker.io/postgres:14.5
          docker run --detach --rm --name gamocosm-sidekiq-redis --network gamocosm-network docker.io/redis:7.0.4

          docker build --file Containerfile --tag gamocosm .

          docker run --rm --network gamocosm-network --env-file template.env gamocosm rails db:setup

          docker run --rm --name gamocosm-tests --network gamocosm-network --env-file template.env gamocosm rails test
workflows:
  version: 2
  doit:
    jobs:
      - test
