version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: large
    steps:
      - checkout
      - run: |
          cp template.env gamocosm.env
          echo 'CI=true' >> gamocosm.env
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> gamocosm.env
          echo "SECRET_KEY_BASE=$(openssl rand -hex 64)" >> gamocosm.env
          echo "RAILS_ENV=test" >> gamocosm.env

          source gamocosm.env

          ssh-keygen -t ed25519 -f id_gamocosm -N ''

          curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz

          docker build --file Containerfile --tag gamocosm-image .

          docker network create gamocosm-network

          docker run --rm --network gamocosm-network --detach --name "$DATABASE_HOST" --env "POSTGRES_USER=$DATABASE_USER" --env "POSTGRES_PASSWORD=$DATABASE_PASSWORD" docker.io/postgres:14.5
          docker run --rm --network gamocosm-network --detach --name "$SIDEKIQ_REDIS_HOST" docker.io/redis:7.0.4

          docker run --rm --network gamocosm-network --env-file gamocosm.env gamocosm-image rails db:setup

          docker create --network gamocosm-network --name gamocosm-test --env-file gamocosm.env gamocosm-image bash -c 'rails test && coveralls report'
          docker cp id_gamocosm gamocosm-test:/gamocosm/
          docker cp .git gamocosm-test:/gamocosm/
          docker cp coveralls gamocosm-test:/usr/local/bin/
          docker start --attach gamocosm-test

workflows:
  run_tests:
    jobs:
      - test
