vanilla:
  name: Vanilla
  versions:
    - latest
    - 1.20.1
    - 1.19.4
    - 1.18.2
    - 1.17.1
  time: 1
  developers:
    - Mojang
  website: https://minecraft.net
  notes: []
vanilla_java8:
  name: Vanilla
  versions:
    - 1.16.5
    - 1.15.2
    - 1.14.4
    - 1.13.2
    - 1.12.2
    - 1.11.2
    - 1.10.2
    - 1.9.4
    - 1.8.9
    - 1.7.10
    - 1.6.4
    - 1.5.2
    - 1.4.7
    - 1.3.2
    - 1.2.5
  time: 1
  developers:
    - Mojang
  website: https://minecraft.net
  notes: []
cuberite:
  name: Cuberite
  versions:
    - "null"
  time: 1
  developers:
    - Cuberite team
  website: https://cuberite.org
  notes: []
vanilla_bedrock:
  name: Bedrock Edition
  versions:
    - 1.18.2.03
    - 1.17.41.01
    - 1.16.221.01
    - 1.14.60.5
  time: 1
  developers:
    - Mojang
  website: https://minecraft.net
  notes: []
forge:
  name: Forge
  versions:
    - 1.19.2-43.2.0
    - 1.18.2-40.1.86
    - 1.17.1-37.1.1
  time: 1
  developers:
    - Minecraft Forge team
  website: https://minecraftforge.net
  notes:
    - Forge 1.17+
forge_java8:
  name: Forge
  versions:
    - 1.16.5-36.2.20
    - 1.15.2-31.2.57
    - 1.14.4-28.2.26
    - 1.13.2-25.0.223
    - 1.12.2-14.23.5.2860
  time: 1
  developers:
    - Minecraft Forge team
  website: https://minecraftforge.net
  notes:
    - Forge 1.12+
forge_old:
  name: Forge
  versions:
    - 1.11.2-13.20.1.2588
    - 1.10.2-12.18.3.2511
    - 1.9.4-12.17.0.2317-1.9.4
    - 1.8.9-11.15.1.2318-1.8.9
    - 1.7.10-10.13.4.1614-1.7.10
  time: 1
  developers:
    - Minecraft Forge team
  website: https://minecraftforge.net
  notes: []
spigotmc:
  name: SpigotMC
  versions:
    - latest
    - 1.18.1
    - 1.17.1
  time: 10
  developers:
    - Spigot team
  website: https://spigotmc.org
  notes:
    - NOT TESTED IN A LONG TIME
    - 1GB+ recommended
    - This involves a long build process. It occasionally fails and you can try again or install it manually
papermc:
  name: PaperMC
  versions:
    - 1.18.1
    - 1.17.1
  time: 1
  developers:
    - PaperMC team
  website: https://papermc.io
  notes:
    - NOT TESTED IN A LONG TIME
    - High performance fork of Spigot
    - Compatible with most Spigot and CraftBukkit plugins
glowstone:
  name: Glowstone
  versions:
    - "null"
  time: 1
  developers:
    - The Glowstone Project
  website: https://www.glowstone.net/
  notes:
    - NOT TESTED IN A LONG TIME
