vanilla:
    versions:
        - { name: Vanilla (Latest), tag: latest }
        - { name: Vanilla (1.15.2), tag: 1.15.2 }
        - { name: Vanilla (1.14.1), tag: 1.14.1 }
        - { name: Vanilla (1.13.2), tag: 1.13.2 }
        - { name: Vanilla (1.12.2), tag: 1.12.2 }
        - { name: Vanilla (1.11.2), tag: 1.11.2 }
        - { name: Vanilla (1.10.2), tag: 1.10.2 }
        - { name: Vanilla (1.9.4), tag: 1.9.4 }
        - { name: Vanilla (1.8.9), tag: 1.8.9 }
        - { name: Vanilla (1.7.10), tag: 1.7.10 }
        - { name: Vanilla (1.7.2), tag: 1.7.2 }
        - { name: Vanilla (1.6.4), tag: 1.6.4 }
        - { name: Vanilla (1.5.2), tag: 1.5.2 }
        - { name: Vanilla (1.4.7), tag: 1.4.7 }
        - { name: Vanilla (1.3.2), tag: 1.3.2 }
        - { name: Vanilla (1.2.5), tag: 1.2.5 }
    time: 1
    developers:
        - Mojang
    website: https://minecraft.net
    notes: []
cuberite:
    versions:
        - { name: Cuberite, tag: "null" }
    time: 1
    developers:
        - Cuberite team
    website: https://cuberite.org
    notes: []
vanilla_bedrock:
    versions:
        - { name: Bedrock Edition (1.16.40), tag: "1.16.40.02" }
        - { name: Bedrock Edition (1.14.32), tag: "1.14.32.1" }
    time: 1
    developers:
        - Mojang
    website: https://minecraft.net
    notes: []
forge:
    versions:
        - { name: Forge (1.12.2-14.23.4.2705), tag: 1.12.2-14.23.4.2705 }
        - { name: Forge (1.10.2-12.18.2.2099), tag: 1.10.2-12.18.2.2099 }
        - { name: Forge (1.9.4-12.17.0.1976), tag: 1.9.4-12.17.0.1976 }
        - { name: Forge (1.8.9-11.15.1.1722), tag: 1.8.9-11.15.1.1722 }
        - { name: Forge (1.8.8-11.14.4.1581), tag: 1.8.8-11.14.4.1581-1.8.8 }
        - { name: Forge (1.8-11.14.4.1563), tag: 1.8-11.14.4.1563 }
        - { name: Forge (1.7.10-10.13.4.1558), tag: 1.7.10-10.13.4.1558-1.7.10 }
    time: 1
    developers:
        - Minecraft Forge team
    website: https://minecraftforge.net
    notes: []
spigot:
    versions:
        - { name: Spigot (Latest), tag: latest }
        - { name: Spigot (1.9.4), tag: 1.9.4 }
        - { name: Spigot (1.9.2), tag: 1.9.2 }
        - { name: Spigot (1.9), tag: 1.9 }
        - { name: Spigot (1.8.8), tag: 1.8.8 }
        - { name: Spigot (1.8.7), tag: 1.8.7 }
        - { name: Spigot (1.8.3), tag: 1.8.3 }
        - { name: Spigot (1.8), tag: 1.8 }
    time: 10
    developers:
        - Spigot team
    website: https://spigotmc.org
    notes:
        - NOT TESTED IN A LONG TIME
        - 1GB+ recommended
        - This involves a long build process. It occasionally fails and you can try again or install it manually
papermc:
    versions:
        - { name: PaperMC (1.16.4), tag: 1.16.4 }
        - { name: PaperMC (1.15.2), tag: 1.15.2 }
        - { name: PaperMC (1.14.4), tag: 1.14.4 }
        - { name: PaperMC (1.13.2), tag: 1.13.2 }
        - { name: PaperMC (1.12.2), tag: 1.12.2 }
    time: 1
    developers:
        - PaperMC team
    website: https://papermc.io
    notes:
        - High performance fork of Spigot
        - Compatible with most Spigot and CraftBukkit plugins
craftbukkit:
    versions:
        - { name: CraftBukkit (1.8), tag: 1.8 }
        - { name: CraftBukkit (beta 1.7.3), tag: b1.7.3 }
    time: 10
    developers:
        - Spigot team
        - CraftBukkit team
    website: https://spigotmc.org
    notes:
        - NOT TESTED IN A LONG TIME
        - 1GB+ recommended
        - This involves a long build process. It occasionally fails and you can try again or install it manually
        - For beta 1.7.3, autoshutdown doesn't work as it doesn't support the query protocol
agrarian_skies:
    versions:
        - { name: Agrarian Skies (1.6.4), tag: 1.6.4 }
    time: 1
    developers:
        - Jadedcat
    website: https://forum.feed-the-beast.com/threads/41906/
    notes:
        - NOT TESTED IN A LONG TIME
        - 2GB+ recommended
        - This script is not updated frequently!
ftb_resurrection:
    versions:
        - { name: FTB Resurrection (1.7.10), tag: 1.7.10 }
    time: 2
    developers:
        - FTB team
    website: https://feed-the-beast.com
    notes:
        - NOT TESTED IN A LONG TIME
        - 2GB+ recommended
        - This script is not updated frequently!
crash_landing:
    versions:
        - { name: Crash Landing (1.6.4), tag: 1.6.4 }
    time: 1
    developers:
        - Iskandar
        - others
    website: https://forum.feed-the-beast.com/threads/46277/
    notes:
        - NOT TESTED IN A LONG TIME
        - 2GB+ recommended
        - This script is not updated frequently!
direwolf20:
    versions:
        - { name: Direwolf20 (1.7.10), tag: 1.7.10 }
    time: 2
    developers:
        - FTB team
    website: https://feed-the-beast.com
    notes:
        - NOT TESTED IN A LONG TIME
        - 2GB+ recommended
        - This script is not updated frequently!
tppi:
    versions:
        - { name: Test Pack Please Ignore (1.6.4), tag: 1.6.4 }
    time: 2
    developers:
        - TPPI team
    website: https://www.reddit.com/r/TestPackPleaseIgnore/
    notes:
        - NOT TESTED IN A LONG TIME
        - 2GB+ recommended
        - This script is not updated frequently!
glowstone:
    versions:
        - { name: Glowstone, tag: "null" }
    time: 1
    developers:
        - The Glowstone Project
    website: https://www.glowstone.net/
    notes:
        - NOT TESTED IN A LONG TIME
